"""Attachment parsing: xlsx / docx / pdf / image fixtures generated by tests/fixtures/make_fixtures.py."""
from __future__ import annotations

import base64
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # backend/ on sys.path (no package install)

from app import attachments, config  # noqa: E402
from tests.fixtures.make_fixtures import make_all  # noqa: E402

XLSX_MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"


@pytest.fixture(scope="module")
def fixtures() -> dict[str, Path]:
    return make_all()


@pytest.fixture(autouse=True)
def _upload_dir(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(config, "UPLOAD_DIR", tmp_path / "uploads")


async def test_xlsx_spec_lines(fixtures: dict[str, Path]) -> None:
    att = await attachments.save_and_parse("spec.xlsx", fixtures["xlsx"].read_bytes(), XLSX_MIME)
    assert att.kind == "excel" and att.id.startswith("att_") and att.path.exists()
    assert attachments.get_attachment(att.id) is att
    assert att.summary == "7 строк, 5 с артикулами"
    by_article = {ln["article"]: ln for ln in att.lines if ln["article"]}
    assert by_article["027228"]["qty"] == 2 and "DRX250" in by_article["027228"]["name"]
    assert by_article["ярп4520"]["qty"] == 10  # Cyrillic article
    assert by_article["221-413"]["qty"] == 50
    assert by_article["310100080_"]["qty"] == 4  # price 9430 must not be taken as qty
    assert by_article["RMNF22TB30"]["qty"] == 1
    cable = next(ln for ln in att.lines if "ВВГ" in (ln["name"] or ""))
    assert cable["article"] is None and cable["qty"] == 300
    manager = next(ln for ln in att.lines if "Менеджер" in ln["raw"])
    assert manager["article"] is None and manager["qty"] is None  # second sheet: header of sheet 1 not applied
    assert "[лист Спецификация]" in att.text and "Кол-во" in att.text
    assert att.as_dict() == {"attachment_id": att.id, "filename": "spec.xlsx", "kind": "excel", "summary": att.summary}


async def test_docx_table_lines(fixtures: dict[str, Path]) -> None:
    att = await attachments.save_and_parse("spec.docx", fixtures["docx"].read_bytes(), DOCX_MIME)
    assert att.kind == "word"
    assert att.summary == "3 строк, 3 с артикулами"
    assert [ln["article"] for ln in att.lines] == ["027228", "ярп4520", "221-413"]
    assert [ln["qty"] for ln in att.lines] == [2, 10, 50]
    assert "Заявка на электротехническую продукцию" in att.text
    assert "самовывоз" in att.text


async def test_pdf_lines(fixtures: dict[str, Path]) -> None:
    att = await attachments.save_and_parse("spec.pdf", fixtures["pdf"].read_bytes(), "application/pdf")
    assert att.kind == "pdf"
    arts = [ln["article"] for ln in att.lines]
    assert "027228" in arts and "221-413" in arts and "LC3-C5E04-359" in arts
    assert "2026-09-23" not in arts  # a date is not an article
    line = next(ln for ln in att.lines if ln["article"] == "221-413")
    assert line["qty"] == 50 and "WAGO" in line["name"]


async def test_image_is_resized_and_exposed_as_block(fixtures: dict[str, Path]) -> None:
    att = await attachments.save_and_parse("photo.png", fixtures["png"].read_bytes(), "image/png")
    assert att.kind == "image" and att.path.suffix == ".jpg" and att.mime == "image/jpeg"
    assert max(att.width, att.height) == 1568 and att.summary.startswith("изображение")
    block = attachments.image_block(att)
    assert block["type"] == "image" and block["source"]["media_type"] == "image/jpeg"
    assert base64.standard_b64decode(block["source"]["data"])[:3] == b"\xff\xd8\xff"
    assert attachments.text_for_llm(att).startswith("[Вложение: photo.png (image)")


async def test_text_for_llm_truncates(fixtures: dict[str, Path]) -> None:
    att = await attachments.save_and_parse("spec.xlsx", fixtures["xlsx"].read_bytes(), XLSX_MIME)
    txt = attachments.text_for_llm(att, max_chars=300)
    assert len(txt) <= 300 and txt.endswith("…")
    full = attachments.text_for_llm(att)
    assert "1. 027228 | АВ DRX250" in full and "Текст файла:" in full


async def test_broken_and_unsupported_files() -> None:
    att = await attachments.save_and_parse("broken.xlsx", b"not really a workbook", XLSX_MIME)
    assert att.kind == "excel" and att.lines == [] and att.summary.startswith("не удалось прочитать")
    with pytest.raises(ValueError):
        await attachments.save_and_parse("archive.zip", b"PK", "application/zip")
    with pytest.raises(ValueError):
        await attachments.save_and_parse("spec.xlsx", b"", XLSX_MIME)
    assert attachments.get_attachment("att_nope") is None


def test_extract_lines_without_header() -> None:
    rows = [
        ["АВ DRX250 MT 3ф 160А 18ka Legrand 027228", "5 шт", "64 920"],
        ["Кабель ВВГнг 3x2,5 ГОСТ", 150],
        ["Розетка Legrand Valena 774420", 1200, 12],
        ["Только текст без чисел"],
    ]
    lines = attachments.extract_lines(rows)
    assert lines[0]["article"] == "027228" and lines[0]["qty"] == 5  # "160А"/"18ka" are units, not articles
    assert lines[1]["article"] is None and lines[1]["qty"] == 150
    assert lines[2]["article"] == "774420" and lines[2]["qty"] == 12  # 1200 looks like a price
    assert lines[3]["article"] is None and lines[3]["qty"] is None and lines[3]["name"] == "Только текст без чисел"


def test_detect_kind() -> None:
    assert attachments.detect_kind("a.XLSX") == "excel"
    assert attachments.detect_kind("photo", "image/jpeg") == "image"
    assert attachments.detect_kind("x.txt", "text/plain") is None
